include:     ['.htaccess']
exclude:     []
timezone: "America/Phoenix"
future: false
highlighter: 'rouge'

excerpt_separator: "<!--more-->"

baseurl: "/"

# PAGINATION
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
