include:     ['.htaccess']
exclude:     []
timezone: "America/Phoenix"
future: false
highlighter: true

excerpt_separator: "\n\n"

baseurl: "/"

# PAGINATION
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
