remote_theme: pages-themes/hacker@v0.2.0
include:     ['.htaccess']
exclude:     []
timezone: "America/Phoenix"
future: false
highlighter: 'rouge'

excerpt_separator: "<!--more-->"

baseurl: "/"

plugins:
- jekyll-paginate
- jekyll-remote-theme

# PAGINATION
paginate: 5
paginate_path: "page:num"
